In [1]:
import pandas as pd
import glob

In [ ]:
files = glob.glob(r"데이터/*playstore_*.csv")
files

['yogiyo_playstore_reviews_7000.csv',
 'ddangyo_reviews_playstore_7000.csv',
 'baemin_reviews_playstore_7000.csv',
 'coupangeats_reviews_playstore_7000.csv']

In [3]:
dfs = [pd.read_csv(f, encoding="utf-8-sig") for f in files]
df_all = pd.concat(dfs, ignore_index=True)
len(df_all)

28000

In [4]:
df_all.columns

Index(['app', 'platform', 'reviewId', 'userName', 'content', 'score',
       'thumbsUpCount', 'at'],
      dtype='object')

In [5]:
df_all.head()

,app,platform,reviewId,userName,content,score,thumbsUpCount,at
0,요기요,playstore,6eb79447-5b96-4ab7-a579-0e14dc1cf730,Google 사용자,고객에게 신경을 안 쓰는 앱입니다. 배달이 정상적으로 되지 않았는데 고객이 불편을 ...,1,0,2025-12-14 21:53
1,요기요,playstore,97780db2-b7ab-4c46-8576-d33308b9b651,시청용유니,뒤에꺼는 해결됐네요. 이제 되네요? 근데 예전보다 좋아진 게 생겼지만 안좋아진 게 ...,5,1,2025-12-14 21:15
2,요기요,playstore,e62e959c-6318-45be-a723-09141c9907c6,Sung-Eun Kim,쓰레기 서비스입니다. 배차가 안되면 짜장면도 한시간 기다려야 하는 상황이네요. 한시...,1,0,2025-12-14 19:16
3,요기요,playstore,db84a055-5512-4f63-aa23-fcf8240e2d9f,정철호,요기요 고객 센터의 대응이 적절하지 않군요 해결이 안될것 같으면 신속히 고객에게 언...,2,0,2025-12-14 18:44
4,요기요,playstore,1e52994f-b25b-4532-9abc-dec271761faf,쫑마루,배민보다좋다생각함,5,0,2025-12-14 17:23

In [6]:
df_all.tail()

,app,platform,reviewId,userName,content,score,thumbsUpCount,at
27995,쿠팡이츠,playstore,bd95cf9e-f6b6-493e-93b0-b1960c418807,워킹맨,아주 좋습니다,5,0,2025-06-27 23:42:41
27996,쿠팡이츠,playstore,6b0e1821-db79-49b1-9ac3-fd3fcf94426a,최재선,만족합니다,5,0,2025-06-27 23:28:36
27997,쿠팡이츠,playstore,35b76a88-4d25-47da-b3ee-29562b897f07,권동욱,배달이 무료배달이 많아서 좋아요,5,0,2025-06-27 22:59:49
27998,쿠팡이츠,playstore,7ffe940a-920d-4821-aa4e-bffe571c0e03,그때 그 언니,좋아 쿠이,5,0,2025-06-27 22:42:12
27999,쿠팡이츠,playstore,0615b6cd-ca6f-4cb3-8165-5e9c2bd9115e,김경연,굿입니다,5,0,2025-06-27 22:07:59

In [7]:
df_all.to_csv("merged_reviews_playstore.csv", index=False, encoding="utf-8-sig")